# Generated by Django 3.2.15 on 2022-10-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipeingredientamount_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredientamount",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="RecipeIngredientAmount",
                to="recipes.ingredient",
                verbose_name="Ингредиент",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredientamount",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="RecipeIngredientAmount",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
    ]
