# Generated by Django 3.2.15 on 2022-10-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221006_1918'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredientamount',
            name='recipe_ingredient_value',
        ),
        migrations.AddConstraint(
            model_name='recipeingredientamount',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient', 'amount'), name='recipe_ingredient_amount'),
        ),
    ]
